# Generated by Django 3.1.2 on 2020-10-23 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='SerialNumber',
            new_name='postSerialNumber',
        ),
    ]
